### ISSUE TITLE
Error linting using black

### ISSUE THREAD

**Issue by igobranco** [openfun/richie#1659]
## Bug Report

**Expected behavior/code**

Error during lint on circleci.

```
Traceback (most recent call last):
  File "/home/circleci/.local/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "src/black/__init__.py", line 1423, in patched_main
  File "src/black/__init__.py", line 1409, in patch_click
ImportError: cannot import name '_unicodefun' from 'click' (/home/circleci/.local/lib/python3.10/site-packages/click/__init__.py)
```

Solution is to upgrade black to version `22.3.0`.
https://github.com/psf/black/issues/2964

**Comment by jbpenrath** [comment]
Fixed by #1658
