### ISSUE TITLE
Cookiecutter - Bootstrap blocked by prompt

### ISSUE THREAD

**Issue by jbpenrath** [openfun/richie#1831]
## Bug Report

**Expected behavior/code**
Once we create a site factory through cookiecutter Richie template, the bootstrap command should work without asking any input.

**Actual Behavior**

**Steps to Reproduce**
1. Follow [docs to create a new site factory](https://github.com/openfun/richie/blob/master/docs/cookiecutter.md) through cookiecutter Richie template
2. `make add-site`
3. Activate site `export RICHIE_SITE=<your_site_name>`
4. `make bootstrap`
5. Then during frontend dependencies installation, you will be ask to install `webpack-cli`.

**Environment**
- Richie version: `master`

**Possible Solution**
Add `webpack-cli` package as dev dependencies to the frontend project within cookiecutter template.

**Additional context/Screenshots**
```
[4/4] Building fresh packages...
success Saved lockfile.
Done in 365.53s.
yarn run v1.22.19
warning package.json: No license field
$ webpack --config node_modules/richie-education/webpack.config.js --output-path ../backend/base/static/richie/js/build --env richie-dependent-build --env richie-settings=overrides.json
CLI for webpack must be installed.
  webpack-cli (https://github.com/webpack/webpack-cli)

We will use "yarn" to install the CLI via "yarn add -D webpack-cli".
Do you want to install 'webpack-cli' (yes/no):
```

**Comment by jbpenrath** [comment]
Once `webpack-cli` installed, error happens next.

```
[webpack-cli] TypeError: Cannot read properties of undefined (reading 'getArguments')
    at WebpackCLI.getBuiltInOptions (/app/src/frontend/node_modules/webpack-cli/lib/webpack-cli.js:745:63)
    at makeCommand.options.entry (/app/src/frontend/node_modules/webpack-cli/lib/webpack-cli.js:870:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebpackCLI.makeCommand (/app/src/frontend/node_modules/webpack-cli/lib/webpack-cli.js:395:31)
    at async loadCommandByName (/app/src/frontend/node_modules/webpack-cli/lib/webpack-cli.js:866:17)
    at async Command.<anonymous> (/app/src/frontend/node_modules/webpack-cli/lib/webpack-cli.js:1262:17)
    at async Command.parseAsync (/app/src/frontend/node_modules/webpack-cli/node_modules/commander/lib/command.js:916:5)
    at async WebpackCLI.run (/app/src/frontend/node_modules/webpack-cli/lib/webpack-cli.js:1286:9)
    at async runCLI (/app/src/frontend/node_modules/webpack-cli/lib/bootstrap.js:9:9)
```

**Comment by jbpenrath** [comment]
The js udpate dependecy pull request #1826 fix this error.

**Comment by onezerobinary** [comment]
I solved with the following steps: 🚀

Go to the frontend folder:

```
cd sites/<name_app>/src/frontend
```

in case, remove the node_modules folder

```
rm -R node_modules
```

remove yarn.lock

```
rm yarn.lock
```

add the following libraries to the package.json

```
"devDependencies": {
	...
	...
	
    "webpack": "5.75.0",
    "webpack-cli": "^5.0.0",
    "source-map-loader":"4.0.1"
  }
```

do yarn and wait untill all the libraries are loaded:

```
yarn
```

go back to the root folder:

```
cd ../../../../.
```

run the command:

```
make bootstrap
```

enjoy 🤙🏽 !!

**Comment by jbpenrath** [comment]
@onezerobinary, the next release of Richie will fix this issue. You do not need anymore to fix that by the hard way !

**Comment by jbpenrath** [comment]
Richie v2.18.0 is out ! :tada:
https://app.circleci.com/pipelines/github/openfun/richie/5546/workflows/74db9b43-e6d4-4063-a4e6-d73424e8296c
