### ISSUE TITLE
First bootstrap raise error dockerflow.health.E001 Could not connect to database

### ISSUE THREAD

**Issue by igobranco** [openfun/richie#2455]
## Bug Report

**Problematic Behavior**
On a clean installation, the bootstrap/run, won't start up the Richie sandbox application.

On an existing installation, to simulate the problem, we need to remove the existing sandbox database and then run it.
```bash
docker rm richie-postgresql-1
make run
```

Logs, 
```
[+] Running 4/0
 ✔ Container richie-elasticsearch-1  Running                                                                                           0.0s
 ✔ Container richie-postgresql-1     Running                                                                                           0.0s
 ✔ Container richie-app-1            Running                                                                                           0.0s
 ✔ Container richie-nginx-1          Running                                                                                           0.0s
Wait for services to be up...
2024/07/02 12:06:57 Waiting for: tcp://postgresql:5432
2024/07/02 12:06:57 Connected to tcp://postgresql:5432
2024/07/02 12:07:01 Waiting for: tcp://elasticsearch:9200
2024/07/02 12:07:01 Connected to tcp://elasticsearch:9200
2024/07/02 12:07:07 Waiting for: tcp://app:8000
2024/07/02 12:07:07 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:08 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:09 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:10 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:11 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:12 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:13 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:14 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:15 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:16 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:17 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:18 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:19 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:20 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:21 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:22 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:23 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:24 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:25 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:26 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:27 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:28 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:29 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:30 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:31 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:32 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:33 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:34 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:35 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:36 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:37 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:38 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:39 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:40 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:41 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:42 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:43 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:44 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:45 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:46 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:47 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:48 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:49 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:50 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:51 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:52 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:53 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:54 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:55 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:56 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:57 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:58 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:07:59 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:08:00 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:08:01 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:08:02 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:08:03 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:08:04 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:08:05 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:08:06 Problem with dial: dial tcp 172.19.0.4:8000: getsockopt: connection refused. Sleeping 1s
2024/07/02 12:08:07 Timeout after 1m0s waiting on dependencies to become available: [tcp://app:8000]
make: *** [Makefile:116: run] Error 1
```

logs
```
$ make logs
app-1  | 🐳(entrypoint) creating user running in the container...
app-1  | 🐳(entrypoint) running your command: /bin/sh -c cd sandbox && python manage.py runserver 0.0.0.0:8000
app-1  | django-configurations version 2.5.1, using configuration Development
app-1  | Performing system checks...
app-1  |
app-1  | Exception in thread django-main-thread:
app-1  | Traceback (most recent call last):
app-1  |   File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
app-1  |     self.run()
app-1  |   File "/usr/local/lib/python3.11/threading.py", line 982, in run
app-1  |     self._target(*self._args, **self._kwargs)
app-1  |   File "/usr/local/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
app-1  |     fn(*args, **kwargs)
app-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
app-1  |     self.check(display_num_errors=True)
app-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 556, in check
app-1  |     raise SystemCheckError(msg)
app-1  | django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:
app-1  |
app-1  | ERRORS:
app-1  | ?: (dockerflow.health.E001) Could not connect to database: connection to server at "postgresql" (172.19.0.2), port 5432 failed: Connection refused
app-1  |        Is the server running on that host and accepting TCP/IP connections?
app-1  |
app-1  |
app-1  | INFOS:
app-1  | ?: (dockerflow.health.I001) Can't connect to database to check migrations
app-1  |
app-1  | System check identified 2 issues (0 silenced).
```

Database logs:
```
$ docker logs richie-postgresql-1
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok


Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
waiting for server to start....2024-07-02 11:55:12.217 UTC [49] LOG:  starting PostgreSQL 12.19 (Debian 12.19-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-07-02 11:55:12.239 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-07-02 11:55:12.381 UTC [50] LOG:  database system was shut down at 2024-07-02 11:53:57 UTC
2024-07-02 11:55:12.416 UTC [49] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE
```

**Expected behavior/code**
To run it.

**Steps to Reproduce**
1. Clone
2. Execute `make bootstrap`, it is failing on the `run` Makefile target.

**Environment**
- Richie version: master
- Platform: Linux

**Possible Solution**

I think the database isn't ready, when the dockerflow is checking if the database connection.
The waits that we have on the Makefile only check if port is open and not if the database is ready to accept connections.
I think we could get some inspiration on: https://stackoverflow.com/a/55835081/2239848

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by igobranco** [comment]
I've tried a fix on docker-compose.yml file, but it can't work, because we have an interpolation of `DB_HOST` on the file.

```patch
diff --git a/docker-compose.yml b/docker-compose.yml
index 14ec0fa48..a7389173f 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -5,6 +5,11 @@ services:
       - "5472:5432"
     env_file:
       - env.d/development/postgresql
+    healthcheck:
+      test: ["CMD-SHELL", "pg_isready -U postgres"]
+      interval: 5s
+      timeout: 5s
+      retries: 300

   mysql:
     image: mysql:8.0
@@ -39,8 +44,11 @@ services:
       - ./data/media:/data/media
       - ./data/smedia:/data/smedia
     depends_on:
-      - "${DB_HOST:-postgresql}"
-      - "elasticsearch"
+      "${DB_HOST:-postgresql}":
+        condition: service_completed_successfully
+        restart: true
+      elasticsearch:
+        condition: service_started
     stdin_open: true
     tty: true
```

Another solution is to split the docker-compose.yml file, so we have a different depends_on db if it is postgreql or mysql.
Ref: https://docs.docker.com/compose/multiple-compose-files/merge/

**Comment by igobranco** [comment]
I've tried to split the docker-compose.yml file, 1 per DB, but I don't know why the docker was blocked indefinitely on Waiting for the database, even when the docker container is healthy.

```
diff --git a/Makefile b/Makefile
index 10bc1fc28..4b51c83a6 100644
--- a/Makefile
+++ b/Makefile
@@ -42,7 +42,7 @@ endif
 DOCKER_UID           = $(shell id -u)
 DOCKER_GID           = $(shell id -g)
 DOCKER_USER          = $(DOCKER_UID):$(DOCKER_GID)
-COMPOSE              = DOCKER_USER=$(DOCKER_USER) DB_HOST=$(DB_HOST) DB_PORT=$(DB_PORT) docker compose
+COMPOSE              = DOCKER_USER=$(DOCKER_USER) DB_HOST=$(DB_HOST) DB_PORT=$(DB_PORT) docker compose -f docker-compose.yml -f docker-compose-$(DB_HOST).yml
 COMPOSE_SSL          = NGINX_CONF=ssl DEV_ENV_FILE=dev-ssl $(COMPOSE)
 COMPOSE_RUN          = $(COMPOSE) run --rm
 COMPOSE_RUN_SSL      = $(COMPOSE_SSL) run --rm
diff --git a/docker-compose.yml b/docker-compose.yml
index 14ec0fa48..e185a3fdf 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,10 +1,4 @@
 services:
-  postgresql:
-    image: postgres:12
-    ports:
-      - "5472:5432"
-    env_file:
-      - env.d/development/postgresql

   mysql:
     image: mysql:8.0
@@ -39,8 +33,8 @@ services:
       - ./data/media:/data/media
       - ./data/smedia:/data/smedia
     depends_on:
-      - "${DB_HOST:-postgresql}"
-      - "elasticsearch"
+      elasticsearch:
+        condition: service_started
     stdin_open: true
     tty: true
```

Waiting indefinitely:
```
$ make run
[+] Running 1/2
 ✔ Container richie-elasticsearch-1  Running                                                                                           0.0s
 ⠼ Container richie-postgresql-1     Waiting                                                                                           200.5s
```
