### ISSUE TITLE
Frontend error on sandbox

### ISSUE THREAD

**Issue by igobranco** [openfun/richie#2520]
## Bug Report

**Problematic Behavior**
The frontend code is not starting up correctly on the browser.

```
Uncaught ReferenceError: exports is not defined
    at ./node_modules/react-intl/node_modules/tslib/tslib.es6.mjs (index.mjs:18278:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./node_modules/react-intl/lib/src/components/createFormattedComponent.js (createFormattedComponent.js:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./node_modules/react-intl/lib/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at index.js:166489:69
    at index.js:166700:2
    at index.js:166701:12
```

**Expected behavior/code**
This error appears on the JS console on every page of Richie sandbox.

**Steps to Reproduce**
Open any page. Open browser console.

**Environment**
- Richie version: master

FYI @sandroscosta @tiago-Salles

**Comment by igobranco** [comment]
@jbpenrath have you seen this ticket?
I talked with @Tiago-Salles and he also have been experience this issue.
Do you have this issue?

**Comment by igobranco** [comment]
I retested this today, at it was fixed! 
FYI @jbpenrath @Tiago-Salles @sandroscosta

**Comment by Tiago-Salles** [comment]
Same to me, it seems resolved.
