### ISSUE TITLE
Make demo-site - the course factory can't use fill_team function

### ISSUE THREAD

**Issue by 2018D** [openfun/richie#393]
## Bug Report

**Expected behavior/code**
The course factory should be able to fill_team

**Actual Behavior**
The course factory of make demo-site blocks the remaining steps of demo-site creation

**Steps to Reproduce**
1. Make bootstrap
2. Make demo-site
3. And then the bug happens!

**Environment**
- Richie version: Master

**Additional context/Screenshots**
Traceback (most recent call last):
  File "sandbox/manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/app/src/richie/apps/core/management/commands/create_demo_site.py", line 263, in handle
    create_demo_site()
  File "/app/src/richie/apps/core/management/commands/create_demo_site.py", line 220, in create_demo_site
    in_navigation=True,
  File "/usr/local/lib/python3.6/site-packages/factory/base.py", line 46, in __call__
    return cls.create(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/factory/base.py", line 563, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/usr/local/lib/python3.6/site-packages/factory/base.py", line 500, in _generate
    return step.build()
  File "/usr/local/lib/python3.6/site-packages/factory/builder.py", line 299, in build
    context=postgen_context,
  File "/usr/local/lib/python3.6/site-packages/factory/declarations.py", line 626, in call
    instance, create, context.value, **context.extra)
  File "/app/src/richie/apps/courses/factories.py", line 219, in fill_team
    **{"persons": person},
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/cms/api.py", line 323, in add_plugin
    plugin = plugin_model(**data)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 573, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'person' is an invalid keyword argument for this function

**Comment by 2018D** [comment]
I got the solution. I'm pushing a branch and making a pr.
